sonar.projectKey=fullstack-project
sonar.projectName=FullStack Project
sonar.projectVersion=1.0

sonar.sources=frontend,backend

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/.git/**,**/**pycache**/**,**/.venv/**
